@startuml

namespace DesignPattern\Creational\AbstractFactory {
    package Factory {
        class AbstractFactory {
                +createHtmlText(string text): Text
                +createJsonText(string text): Text
        }
    }

    package Texts {
        interface Text {
            #$text: string
        }
        class HtmlText
        class JsonText

        HtmlText .up.|> Text : implement
        JsonText .up.|> Text : implement
    }

    Factory o-- Texts : aggregation
}

@enduml